name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - uses: actions/docker/login@master
      secrets: ["DOCKER_USERNAME", "DOCKER_PASSWORD"]
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cuotos/kdebugimage:latest
