name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: cuotos
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v1
    - uses: actions/docker/cli@master
      with:
        args: 'build -t cuotos/kdebugimage:latest .'
    - uses: actions/docker/cli@master
      with:
        args: push cuotos/kdebugimage:latest