name: Docker Image CI master

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    
    - name: build docker image
      run: docker build -t ${{ github.repository }}:latest .
    
    - name: Log into registry
      env:
        DOCKER_USERNAME: cuotos
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ github.actor }} --password-stdin
    
    - name: push image
      run: docker push ${{ github.repository }}:latest
