name: Docker Image CI

on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: cuotos
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: actions/checkout@v1
    
    - uses: actions/docker/cli@master
      with:
        args: 'build -t theimage .'

    - uses: actions/docker/tag@master
      with:
        args: "theimage cuotos/kdebugimage"
    
    - uses: actions/docker/cli@master
      if: github.ref != 'master'
      with:
        args: push cuotos/kdebugimage:github.ref

    - uses: actions/docker/cli@master
      if: github.ref == 'master'
      with:
        args: push cuotos/kdebugimage:latest