name: Docker Image CI master

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - env:
        DOCKER_USERNAME: cuotos
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ github.actor }} --password-stdin
