name: goreleaser

on:
  push:
    pull_request:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: cuotos
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: release
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
